services:
  n_calc:
    container_name: noten_calculator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      # Optional: no source mounting needed in preview mode
      - node_modules:/app/node_modules
    #command: sh -c "pnpm install && pnpm build && pnpm preview --host"
    restart: unless-stopped
    networks:
      - nginx_proxy_manager_default

volumes:
  node_modules:

networks:
  nginx_proxy_manager_default:
    external: false