version: '3.8'
services:
  reactapp:
    container_name: noten_calculator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    restart: unless-stopped
    volumes:
      # Mount source code for hot reloading, but exclude node_modules
      - ./src:/app/src
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./vite.config.ts:/app/vite.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tsconfig.app.json:/app/tsconfig.app.json
      - ./package.json:/app/package.json
      # Use a named volume for node_modules to avoid conflicts
      - node_modules:/app/node_modules
    # Make sure it's on the same network as NPM
    networks:
      - nginx_proxy_manager_default

networks:
  nginx_proxy_manager_default:
    external: true

volumes:
  node_modules: